#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library_path = "../game/bin/libfps.{}.{}.framework/libfps.{}.{}".format(
        env["platform"], env["target"], env["platform"], env["target"]
    )
else:
    library_path = "../game/bin/libfps{}{}".format(env["suffix"], env["SHLIBSUFFIX"])

library = env.SharedLibrary(library_path, source=sources)

Default(library)
